# Generated by Django 2.0.3 on 2018-06-04 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sahm', '0003_auto_20180407_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(blank=True, max_length=200, null=True)),
                ('dia', models.DateField(help_text='Dia da Monitoria', verbose_name='Dia da Monitoria')),
                ('hora_inicio', models.TimeField(help_text='Hora de Inicio', verbose_name='Hora de Inicio')),
                ('hora_termino', models.TimeField(help_text='Hora de Termino', verbose_name='Hora de Termino')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
