# Generated by Django 2.0.3 on 2018-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahm', '0005_auto_20180604_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='sala',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='dia',
            field=models.DateField(blank=True, help_text='Dia da Monitoria', null=True, verbose_name='Dia da Monitoria'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de Inicio', null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='hora_termino',
            field=models.TimeField(blank=True, help_text='Hora de Termino', null=True, verbose_name='Hora de Termino'),
        ),
    ]
