# Generated by Django 2.0.3 on 2018-06-12 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahm', '0006_auto_20180611_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='user',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahm.Monitor'),
        ),
    ]
