# Generated by Django 2.0.3 on 2018-06-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahm', '0008_auto_20180612_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahm.Monitor'),
        ),
    ]
