# Generated by Django 2.0.3 on 2018-06-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahm', '0010_auto_20180613_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
